context:
  version: "4.0.4"

package:
  name: pueue
  version: ${{ version }}

source:
  url: https://github.com/Nukesor/pueue/archive/v${{ version }}.tar.gz
  sha256: 236a47a1cc74721998f4de3eff5062efe8e73c56c05aa19e64fef2e5ee55700f

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - pueue --help

about:
  license: MIT
  license_file:
    - LICENSE.MIT
    - LICENSE.APACHE
    - THIRDPARTY.yml
  summary: Command-line tool for managing long-running shell commands
  homepage: https://github.com/Nukesor/pueue
  repository: https://github.com/Nukesor/pueue

extra:
  recipe-maintainers:
    - danielnachun
