context:
  version: 3.4.1

package:
  name: pueue
  version: ${{ version }}

source:
  url: https://github.com/Nukesor/pueue/archive/v${{ version }}.tar.gz
  sha256: 868710de128db49e0a0c4ddee127dfc0e19b20cbdfd4a9d53d5ed792c5538244

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - pueue --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Command-line tool for managing long-running shell commands
  homepage: https://github.com/Nukesor/pueue
  repository: https://github.com/Nukesor/pueue

extra:
  recipe-maintainers:
    - danielnachun
