context:
  version: "4.0.2"

package:
  name: pueue
  version: ${{ version }}

source:
  url: https://github.com/Nukesor/pueue/archive/v${{ version }}.tar.gz
  sha256: 059ee9688cb8b1ce46284f5ad58de21911b6af50098d29598085d2b9dbd432ab

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - pueue --help

about:
  license: MIT
  license_file:
    - LICENSE.MIT
    - LICENSE.APACHE
    - THIRDPARTY.yml
  summary: Command-line tool for managing long-running shell commands
  homepage: https://github.com/Nukesor/pueue
  repository: https://github.com/Nukesor/pueue

extra:
  recipe-maintainers:
    - danielnachun
